Make NumPy available:

In [1]:
import numpy as np

## Exercise 07.1 (indexing and timing)

Create two very long NumPy arrays `x` and `y` and sum the arrays using:

1. The NumPy addition syntax, `z = x + y`; and
2. A `for` loop that computes the sum entry-by-entry

Compare the time required for the two approaches for vectors of different lengths (use a very long vector for 
the timing). The values of the array entries are not important for this test. Use `%time` to report the time.

*Hint:* To loop over an array using indices, try a construction like:

In [2]:
x = np.ones(10)
y = np.ones(len(x))
for i in range(len(x)):
    print(x[i]*y[i])

1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0


#### (1) Add two vectors using built-in addition operator:

In [3]:
# YOUR CODE HERE
x = np.random.rand(10000000) # 10 million
y = np.random.rand(len(x))

%time z1 = x + y

CPU times: user 12 ms, sys: 20 ms, total: 32 ms
Wall time: 33.1 ms


#### (2) Add two vectors using own implementation:

In [4]:
# YOUR CODE HERE
def sum_arrays(a,b):
    c = [0]*len(a)
    for i in range(len(a)):
        c[i] = a[i] + b[i]
    return c

%time z2 = sum_arrays(x,y)

CPU times: user 2.68 s, sys: 120 ms, total: 2.8 s
Wall time: 2.8 s


## Exercise 07.2 (member functions and slicing)

Anonymised scores (out of 60) for an examination are stored in a NumPy array. Write:

1. A function that takes a NumPy array of the raw scores and returns the scores as percentages, sorted from 
   lowest to highest (try using `scores.sort()`, where `scores` is a NumPy array holding the scores).
1. A function that returns the maximum, minimum and mean of the raw scores as a dictionary with the 
   keys '`min`', '`max`' and '`mean`'. Use the NumPy array functions `min()`, `max()` and `mean()` to do the 
   computation, e.g. `max = scores.max()`.  
   
   Design your function for the min, max and mean to optionally exclude the highest and lowest scores from the 
   computation of the min, max and mean. 
   
   *Hint:* sort the array of scores and use array slicing to exclude
   the first and the last entries.

Use the scores 
```python
scores = np.array([58.0, 35.0, 24.0, 42, 7.8])
```
to test your functions.

In [5]:
def to_percentage_and_sort(scores):
    # YOUR CODE HERE
    percentage = scores*100/60
    percentage.sort()
    return percentage

def statistics(scores, exclude=False):
    # YOUR CODE HERE
    scores.sort()
    if exclude:
        scores = scores[1:-1]

    stats = {'min': scores.min(), 
             'max': scores.max(),
             'mean': scores.mean()}
    
    return stats

In [6]:
scores = np.array([58.0, 35.0, 24.0, 42, 7.8])
assert np.isclose(to_percentage_and_sort(scores), [ 13.0, 40.0, 58.33333333,  70.0, 96.66666667]).all()

s0 = statistics(scores)
assert round(s0["min"] - 7.8, 10) == 0.0
assert round(s0["mean"] - 33.36, 10) == 0.0
assert round(s0["max"] - 58.0, 10) == 0.0

s1 = statistics(scores, True)
assert round(s1["min"] - 24.0, 10) == 0.0
assert round(s1["mean"] - 33.666666666666666667, 10) == 0.0
assert round(s1["max"] - 42.0, 10) == 0.0

## Exercise 07.3 (slicing)

For the two-dimensional array

In [7]:
A = np.array([[4.0, 7.0, -2.43, 67.1],
             [-4.0, 64.0, 54.7, -3.33],
             [2.43, 23.2, 3.64, 4.11],
             [1.2, 2.5, -113.2, 323.22]])
print(A)

[[   4.      7.     -2.43   67.1 ]
 [  -4.     64.     54.7    -3.33]
 [   2.43   23.2     3.64    4.11]
 [   1.2     2.5  -113.2   323.22]]


use array slicing for the below operations, printing the results to the screen to check. Try to use array slicing such that your code would still work if the dimensions of `A` were enlarged.



#### 1. Extract the third column as a 1D array

In [8]:
# YOUR CODE HERE
print(A[:,2])

[  -2.43   54.7     3.64 -113.2 ]


#### 2. Extract the first two rows as a 2D sub-array

In [9]:
# YOUR CODE HERE
print(A[0:2,:])

[[  4.     7.    -2.43  67.1 ]
 [ -4.    64.    54.7   -3.33]]


#### 3.  Extract the bottom-right $2 \times 2$ block as a 2D sub-array

In [10]:
# YOUR CODE HERE
print(A[-2:,-2:])

[[   3.64    4.11]
 [-113.2   323.22]]


#### 4. Sum the last column

In [11]:
# YOUR CODE HERE
print(np.sum(A[:,-1]))

391.1


#### Compute transpose

Compute the transpose of `A` (search online to find the function/syntax to do this).

In [12]:
# YOUR CODE HERE
print(np.transpose(A))

[[   4.     -4.      2.43    1.2 ]
 [   7.     64.     23.2     2.5 ]
 [  -2.43   54.7     3.64 -113.2 ]
 [  67.1    -3.33    4.11  323.22]]


## Exercise 07.4 (optional extension)

In a previous exercise you implemented the bisection algorithm to find approximate roots of a mathematical function. Use the SciPy bisection function `optimize.bisect` (http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.optimize.bisect.html) to find roots of the mathematical function that was used in the previous exercise. Compare the results computed by SciPy and your program from the earlier exercise, and compare the computational time (using `%time`).

In [13]:
from scipy import optimize

# YOUR CODE HERE
def f(x):
    return x**3 - 6*x**2 + 4*x + 12

# From Exercise 02.2(1)
def ex2_bisection():
    # Initial end points
    x0 = 3.0
    x1 = 6.0

    # Use 41 iterations so the comparison with scipy is fair
    for n in range(41):
        # Compute midpoint
        x_mid = (x0 + x1)/2

        # Evaluate function at left end-point and at midpoint
        f0 = x0**3 - 6*x0**2 + 4*x0 + 12
        f = x_mid**3 - 6*x_mid**2 + 4*x_mid + 12

        # YOUR CODE HERE
        if f*f0 < 0:
            x1 = x_mid
        else:
            x0 = x_mid

    return(x_mid)

print("Answer using scipy:")
%time ans_scipy = optimize.bisect(f, 3, 6) # optimize.bisect(f, 3, 6, full_output=True)
print(ans_scipy)
print("------------")
print("Answer using exercise 2 for loop:")
%time ans_ex2 = ex2_bisection()
print(ans_ex2)

Answer using scipy:
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 42.7 µs
4.534070196722951
------------
Answer using exercise 2 for loop:
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 51.5 µs
4.534070196722951
